# Generated by Django 4.0.2 on 2022-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_subject', models.CharField(max_length=250)),
                ('user_massege', models.CharField(max_length=500)),
            ],
        ),
    ]
