# Generated by Django 4.0.2 on 2022-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_date', models.DateTimeField()),
                ('img_image', models.FileField(default=None, max_length=150, upload_to='images/')),
            ],
        ),
    ]
